export const mockData: HistoryItem[] = [
  {
    date: "2023-01-01",
    id: 1,
    name: "John Doe",
    photo: "base64_string_1",
    result: "Pass",
    status: "Active",
  },
  {
    date: "2023-02-15",
    id: 2,
    name: "Jane Smith",
    photo: "base64_string_2",
    result: "Fail",
    status: "Inactive",
  },
  {
    date: "2023-03-20",
    id: 3,
    name: "Mark Johnson",
    photo: "base64_string_3",
    result: "Pending",
    status: "Active",
  },
  {
    date: "2023-04-10",
    id: 4,
    name: "Emily Brown",
    photo: "base64_string_4",
    result: "Pass",
    status: "Inactive",
  },
  {
    date: "2023-05-05",
    id: 5,
    name: "Michael White",
    photo: "base64_string_5",
    result: "Fail",
    status: "Active",
  },
  {
    date: "2023-06-25",
    id: 6,
    name: "Alice Green",
    photo: "base64_string_6",
    result: "Pass",
    status: "Inactive",
  },
  {
    date: "2023-07-14",
    id: 7,
    name: "Jack Black",
    photo: "base64_string_7",
    result: "Fail",
    status: "Active",
  },
  {
    date: "2023-08-30",
    id: 8,
    name: "Rachel Taylor",
    photo: "base64_string_8",
    result: "Pending",
    status: "Active",
  },
  {
    date: "2023-09-19",
    id: 9,
    name: "Kevin Lee",
    photo: "base64_string_9",
    result: "Pass",
    status: "Active",
  },
  {
    date: "2023-10-08",
    id: 10,
    name: "Sarah Carter",
    photo: "base64_string_10",
    result: "Fail",
    status: "Inactive",
  },
];
