version: "3.3"

services:
  frontend:
    build:
      context: ../atomic/
      dockerfile: Dockerfile
    ports:
      - "5181:5181"
  backend:
    build:
      context: ../go-backend/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DOCKER_MODE=1
    ports:
      - "8091:8091"
    network_mode: host
  python-backend:
      build:
        context: ../python-backend/
        dockerfile: Dockerfile
      restart: always
      environment:
        - DOCKER_MODE=1
      ports:
        - "8001:8001"
      network_mode: host
  bot:
    build:
      context: ../Bot/
      dockerfile: Dockerfile
    ports:
      - "8444:8444"
    command: python main.py

