version: "3.3"

services:
  backend:
    build:
      context: ../go-backend/
      dockerfile: Dockerfile
    restart: always
    environment:
      - DOCKER_MODE=1
    ports:
      - "8091:8091"
    network_mode: host
  bot:
    build:
      context: ../Bot/
      dockerfile: Dockerfile
    ports:
      - "8444:8444"
    command: python main.py